---
-
 
  hosts:  multi
  become: true

  tasks:
  
  - name: Update all packages RedHat and Ubuntu
    yum:
      name: '*'
      state: latest
    notify: Update installed

  - name: Install Apache and PHP packages RedHat
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    notify: Apache and PHP instaled
    when: ansible_os_family == "RedHat"

  - name: Install Apache and PHP packages Ubuntu
    apt:
      name:
        -  apache2
        -  php
      state: latest
      update_cache: yes
    notify: Apache and PHP instaled ubuntu
    when: ansible_os_family == "Debian"

  handlers:
   - name: Update installed
     debug:
       msg: Update DOWN!!!
   - name: Apache and PHP instaled
     debug:
       msg: Apache and PHP instaled on RedHat!!!
   - name: Apache and PHP instaled ubuntu
     debug:
       msg: Apache and PHP instaled on Ubuntu!!!

...
