---
-
  hosts: multi
  become: true

  tasks:
 
  - name: Remove Apache
    yum:
      name: httpd
      state: absent
    notify: Apache removed
#    when: ansible_os_family == "Redhat"

  - name: Remove Apache Ubuntu
    apt:
      name: apache2 
      state: absent
    notify: Apache removed
    when: ansible_os_family == "Debian"

  - name: Remove Nginx 
    yum:
      name: nginx
      state: absent
    notify: Nginx removed

  - name: Remove php support for apache
    yum:
      name: php
      state: absent
    notify: PHP removed
#    when: ansible_os_family == "Redhat"

  handlers:
   - name: Apache removed 
     debug:
       msg: "!!! Apache REMOVED !!!"
   - name: PHP removed
     debug:
       msg: "!!! PHP support REMOVED !!!"
   - name: Nginx removed
     debug:
       msg: NGINX REMOVED
...
