---
- name: Update packages on all servers
 
  hosts:  multi
  become: true

  tasks:
  - name: Update repo cache (RedHat)
    tags: always
    yum:
      state: latest
      update_cache: yes
    notify: Update installed
    changed_when: false
    when: ansible_os_family == "RedHat"

  - name: Update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    notify: Update installed
    changed_when: false
    when: ansible_os_family == "Debian"

  handlers:
   - name: Update installed
     debug:
       msg: Update FINSHED!!!

- name: create users
  hosts: multi
  become: true

  tasks:

    - name: add ssh key to user
      tags: always
      authorized_key:
        user: andreja
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVTSsyHb7bDUWQLupquecXnAiR/TLfQVr2mWtfVZXPRWmqG/sdGj2u2rvQOR1ox9rm9Dp2/jniuOtQR5Di3by7ISDNV2psW/dDCBS+NYfu1aFP9B+2jejIaWOO9aKS4VeZEVsMuYVOSsnzfH0bk1Lwpx9KRznXAljW6+fzVNLcgsAvNNdn21j7octv6I289Q5Q04fxmRsOCs5s2i7NWvgbr1DCN6/xURO6XNL93DbrggFXj/5mPNq1izRhOcrlJCur1DDTHa4VFfI+pUG3uII98UkQVo7ojdtiKo0wwfzMSKMtqysyKR2ZHX+d2DtmpCe0isAmalQwxtsdEniU5dvx ec2-user@ansible-engine"

- name: Install zip and terraform on local
  hosts: local
  become: true

  tasks:
   - name: install zip
     package:
       name: unzip

   - name: install terraform
     unarchive:
       src: https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root

- name: Install Apache and PHP only on web_servers

  hosts: web_servers
  become: true
 
  tasks:
  - name: Install Apache and PHP packages RedHat
    tags: apache,redhat,httpd
    yum:
      name: 
        - httpd
        - php
      state: latest
    notify: Apache and PHP instaled
    when: ansible_os_family == "RedHat"

  - name: Start httpd server (RedHat)
    tags: apache,redhat,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    notify: httpd started
    when: ansible_os_family == "RedHat"

  - name: Install Apache and PHP packages Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        -  apache2
        -  php
      state: latest
    notify: Apache and PHP instaled ubuntu
    when: ansible_os_family == "Debian"

  - name: copy default html files
    tags: apache,redhat,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  handlers:
   - name: Apache and PHP instaled
     debug:
       msg: Apache and PHP instaled on RedHat!!!
   - name: httpd started
     debug:
       msg: httpd server started!!!
   - name: Apache and PHP instaled ubuntu
     debug:
       msg: Apache and PHP instaled on Ubuntu!!!


- name: install mariadb package

  hosts: db_servers
  become: true

  tasks:
  - name: install mariadb
    tags: redhat,db,mariadb
    yum:
      name: mariadb-server
      state: latest
    notify: mariaDB install
    when: ansible_os_family == "RedHat" 

  handlers:
   - name: mariaDB install
     debug:
       msg: MariaDB installed!!!

- name: file-servers

  hosts: file_servers
  become: true

  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
    notify: samba instalation

  handlers:
   - name: samba instalation
     debug:
       msg: Samba instaled!!! 

...
