---
- name: Update packages on all servers
 
  hosts:  multi
  become: true

  tasks:
  - name: Update repo cache (RedHat)
    tags: always
    yum:
      state: latest
      update_cache: yes
    notify: Update installed
    changed_when: false
    when: ansible_os_family == "RedHat"

  - name: Update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    notify: Update installed
    changed_when: false
    when: ansible_os_family == "Debian"

  handlers:
   - name: Update installed
     debug:
       msg: CACHE UPDATED!!!

- name: create users
  hosts: multi
  become: true
  roles:
    - base

- name: Install zip and terraform on local
  hosts: local
  become: true
  roles:
    - local
   
- name: Install Apache and PHP only on web_servers
  hosts: web_servers
  become: true
  roles:
    - web_servers

- name: install mariadb package
  hosts: db_servers
  become: true
  roles:
    - db_servers

- name: file-servers
  hosts: file_servers
  become: true
  roles:
    - file_servers
    


...
